version: "3"

services:
  nginx-proxy-managaer:
    container_name: nginx-proxy-manger
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./nginx-proxy-manager/data:/data
      - ./nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 8000:8000
      - 9443:9443
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

  # pihole:
  #   container_name: pihole
  #   image: pihole/pihole:latest
  #   # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
  #     - "8080:80/tcp"
  #   env_file:
  #     - pihole.env
  #   environment:
  #     TZ: 'ASIA/DHAKA'
  #   volumes:
  #     - './pihole/etc-pihole:/etc/pihole'
  #     - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
  #   restart: unless-stopped
  # https://firebog.net/
